import React, { useState, useEffect } from 'react';
import { FileSpreadsheet, Cpu, Sparkles, RefreshCw, Upload, Download, Code, FileText } from 'lucide-react';
import { aiService } from '../../utils/aiService';
import { parseMarkdown } from '../../utils/markdownParser';

export const CSVSchemaDiffTool: React.FC = () => {
  const [csvA, setCsvA] = useState(`id,name,email,role,status
1,Alice,alice@app.com,admin,active
2,Bob,bob@app.com,user,active
3,Charlie,charlie@app.com,user,pending`);

  const [csvB, setCsvB] = useState(`id,name,email,role,status,last_login
1,Alice,alice@app.com,admin,active,2026-07-27
2,Bob,bob@app.com,editor,active,2026-07-26
4,David,david@app.com,user,active,2026-07-25`);

  const [sqlDialect, setSqlDialect] = useState<'postgres' | 'mysql' | 'sqlite'>('postgres');

  // Local AI State
  const [models, setModels] = useState<string[]>([]);
  const [selectedModel, setSelectedModel] = useState<string>('');
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [aiOutput, setAiOutput] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchModels = async () => {
      const { status, models } = await aiService.checkOllama();
      if (status && models.length > 0) {
        setModels(models);
        const saved = aiService.getSelectedOllamaModel();
        if (saved && models.includes(saved)) {
          setSelectedModel(saved);
        } else {
          setSelectedModel(models[0]);
        }
      }
    };
    fetchModels();
  }, []);

  const handleFileUploadA = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = (evt) => setCsvA(evt.target?.result as string);
    reader.readAsText(file);
  };

  const handleFileUploadB = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = (evt) => setCsvB(evt.target?.result as string);
    reader.readAsText(file);
  };

  const parseCsvLines = (text: string) => text.trim().split('\n').filter(Boolean);

  const linesA = parseCsvLines(csvA);
  const linesB = parseCsvLines(csvB);

  const colsA = linesA[0]?.split(',') || [];
  const colsB = linesB[0]?.split(',') || [];

  const rowsCountA = Math.max(0, linesA.length - 1);
  const rowsCountB = Math.max(0, linesB.length - 1);

  const addedCols = colsB.filter((c) => !colsA.includes(c));
  const removedCols = colsA.filter((c) => !colsB.includes(c));
  const commonCols = colsA.filter((c) => colsB.includes(c));

  const generateSqlMigration = () => {
    const alterAdd = addedCols
      .map((c) =>
        sqlDialect === 'postgres'
          ? `ALTER TABLE dataset ADD COLUMN ${c} VARCHAR(255);`
          : sqlDialect === 'mysql'
          ? `ALTER TABLE dataset ADD ${c} VARCHAR(255);`
          : `ALTER TABLE dataset ADD COLUMN ${c} TEXT;`
      )
      .join('\n');

    const alterDrop = removedCols
      .map((c) =>
        sqlDialect === 'sqlite'
          ? `-- SQLite does not support DROP COLUMN directly: ALTER TABLE dataset DROP COLUMN ${c};`
          : `ALTER TABLE dataset DROP COLUMN ${c};`
      )
      .join('\n');

    return `-- Automated CSV Schema Migration Script (${sqlDialect.toUpperCase()})\n-- Generated by DomoDomo Client-Side AI Tool\n\n${alterAdd}\n${alterDrop}`;
  };

  const sqlScript = generateSqlMigration();

  const handleDownloadMigrationSql = () => {
    const blob = new Blob([sqlScript], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.download = `schema_migration_${sqlDialect}.sql`;
    a.href = url;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadDiffReport = () => {
    const report = `CSV Schema & Data Drift Diagnostic Report\n\nDataset A Rows: ${rowsCountA}\nDataset B Rows: ${rowsCountB}\nAdded Columns: ${addedCols.join(', ') || 'None'}\nRemoved Columns: ${removedCols.join(', ') || 'None'}\n\nSQL Migration Script:\n${sqlScript}`;
    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.download = 'csv_schema_drift_report.txt';
    a.href = url;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleRunAiDataDiff = async () => {
    if (!selectedModel) return;
    setIsAnalyzing(true);
    setError(null);

    const prompt = `Dataset A Header: ${colsA.join(', ')} (${rowsCountA} rows)\nDataset B Header: ${colsB.join(', ')} (${rowsCountB} rows)\n\nSample A:\n${csvA.slice(0, 500)}\n\nSample B:\n${csvB.slice(0, 500)}`;

    const systemPrompt = `You are a Senior Database Engineer & Data Migration Architect.
Compare Dataset A and Dataset B:
1. Identify added/deleted columns and data type schema shifts.
2. Highlight row count variances, missing value rates, and data drift across keys.
3. Provide hardened SQL DDL migration queries to sync the tables.
Format cleanly with markdown tables and highlighted code blocks.`;

    try {
      const response = await aiService.generateTextOllama(selectedModel, prompt, 2048, systemPrompt);
      setAiOutput(response);
    } catch (err: any) {
      setError(err.message || 'Failed to analyze CSV schema diff with Local AI.');
    } finally {
      setIsAnalyzing(false);
    }
  };

  return (
    <div className="flex flex-col gap-6 max-w-5xl mx-auto w-full">
      {/* Header */}
      <div className="glass-card p-6 border-[#2A2D30] bg-[#18191B] flex flex-col gap-4 text-left rounded-2xl">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="bg-[#3C6B4D]/10 text-[#3C6B4D] border border-[#3C6B4D]/20 p-2.5 rounded-xl">
              <FileSpreadsheet size={24} />
            </div>
            <div>
              <h3 className="font-bold text-[#ECEBE9] text-xl">AI CSV Schema & Data Drift Diagnostic Tool</h3>
              <p className="text-[#A3A09B] text-xs mt-1">
                Compare two CSV spreadsheets column-by-column, detect structural schema shifts, generate database migration SQL scripts, and audit drift with Local AI.
              </p>
            </div>
          </div>
          {models.length > 0 && (
            <div className="flex items-center gap-2 bg-[#111213] p-2 rounded-xl border border-[#2A2D30]">
              <Cpu size={16} className="text-[#3C6B4D]" />
              <select
                value={selectedModel}
                onChange={(e) => setSelectedModel(e.target.value)}
                className="bg-transparent text-xs text-[#ECEBE9] focus:outline-none cursor-pointer"
              >
                {models.map((m) => (
                  <option key={m} value={m} className="bg-[#18191B] text-[#ECEBE9]">
                    {m}
                  </option>
                ))}
              </select>
            </div>
          )}
        </div>
      </div>

      {/* Summary KPI Metrics */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
        <div className="glass-card p-4 border-[#2A2D30] bg-[#18191B] rounded-2xl text-left">
          <p className="text-[10px] text-[#A3A09B]">Dataset A Columns</p>
          <p className="text-xl font-bold text-[#ECEBE9] font-mono mt-1">{colsA.length} Cols ({rowsCountA} Rows)</p>
        </div>
        <div className="glass-card p-4 border-[#2A2D30] bg-[#18191B] rounded-2xl text-left">
          <p className="text-[10px] text-[#A3A09B]">Dataset B Columns</p>
          <p className="text-xl font-bold text-[#3C6B4D] font-mono mt-1">{colsB.length} Cols ({rowsCountB} Rows)</p>
        </div>
        <div className="glass-card p-4 border-[#2A2D30] bg-[#18191B] rounded-2xl text-left">
          <p className="text-[10px] text-[#A3A09B]">Added Columns</p>
          <p className="text-xl font-bold text-emerald-400 font-mono mt-1">+{addedCols.length}</p>
        </div>
        <div className="glass-card p-4 border-[#2A2D30] bg-[#18191B] rounded-2xl text-left">
          <p className="text-[10px] text-[#A3A09B]">Removed Columns</p>
          <p className="text-xl font-bold text-rose-400 font-mono mt-1">-{removedCols.length}</p>
        </div>
      </div>

      {/* Main Grid: Dataset Inputs */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Dataset A */}
        <div className="glass-card p-6 border-[#2A2D30] bg-[#18191B] rounded-2xl flex flex-col gap-4 text-left">
          <div className="flex items-center justify-between">
            <h4 className="text-sm font-semibold text-[#ECEBE9]">Dataset A (Baseline CSV)</h4>
            <label className="flex items-center gap-1.5 text-xs text-[#3C6B4D] hover:underline cursor-pointer font-semibold">
              <Upload size={14} />
              Upload CSV A
              <input type="file" accept=".csv,.tsv,.txt" onChange={handleFileUploadA} className="hidden" />
            </label>
          </div>
          <textarea
            value={csvA}
            onChange={(e) => setCsvA(e.target.value)}
            rows={8}
            className="bg-[#111213] border border-[#2A2D30] text-[#ECEBE9] text-xs p-3.5 rounded-xl font-mono resize-none focus:outline-none focus:border-[#3C6B4D]"
          />
        </div>

        {/* Dataset B */}
        <div className="glass-card p-6 border-[#2A2D30] bg-[#18191B] rounded-2xl flex flex-col gap-4 text-left">
          <div className="flex items-center justify-between">
            <h4 className="text-sm font-semibold text-[#ECEBE9]">Dataset B (Target / New CSV)</h4>
            <label className="flex items-center gap-1.5 text-xs text-[#3C6B4D] hover:underline cursor-pointer font-semibold">
              <Upload size={14} />
              Upload CSV B
              <input type="file" accept=".csv,.tsv,.txt" onChange={handleFileUploadB} className="hidden" />
            </label>
          </div>
          <textarea
            value={csvB}
            onChange={(e) => setCsvB(e.target.value)}
            rows={8}
            className="bg-[#111213] border border-[#2A2D30] text-[#ECEBE9] text-xs p-3.5 rounded-xl font-mono resize-none focus:outline-none focus:border-[#3C6B4D]"
          />
        </div>
      </div>

      {/* Schema Difference Comparison Table */}
      <div className="glass-card p-6 border-[#2A2D30] bg-[#18191B] rounded-2xl flex flex-col gap-4 text-left">
        <h4 className="font-bold text-[#ECEBE9] text-sm">Column Schema Comparison Matrix</h4>

        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          <div className="bg-[#111213] p-4 rounded-xl border border-[#2A2D30]">
            <p className="text-xs font-bold text-emerald-400 mb-2">Added Columns (+)</p>
            {addedCols.length > 0 ? (
              addedCols.map((c) => (
                <span key={c} className="inline-block bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 font-mono text-xs px-2 py-1 rounded-md m-0.5">
                  +{c}
                </span>
              ))
            ) : (
              <p className="text-xs text-[#A3A09B]">No new columns added.</p>
            )}
          </div>

          <div className="bg-[#111213] p-4 rounded-xl border border-[#2A2D30]">
            <p className="text-xs font-bold text-rose-400 mb-2">Removed Columns (-)</p>
            {removedCols.length > 0 ? (
              removedCols.map((c) => (
                <span key={c} className="inline-block bg-rose-500/10 text-rose-400 border border-rose-500/20 font-mono text-xs px-2 py-1 rounded-md m-0.5">
                  -{c}
                </span>
              ))
            ) : (
              <p className="text-xs text-[#A3A09B]">No columns removed.</p>
            )}
          </div>

          <div className="bg-[#111213] p-4 rounded-xl border border-[#2A2D30]">
            <p className="text-xs font-bold text-[#ECEBE9] mb-2">Matching Preserved Columns</p>
            {commonCols.map((c) => (
              <span key={c} className="inline-block bg-[#18191B] text-[#ECEBE9] border border-[#2A2D30] font-mono text-xs px-2 py-1 rounded-md m-0.5">
                {c}
              </span>
            ))}
          </div>
        </div>
      </div>

      {/* SQL Migration Generator */}
      <div className="glass-card p-6 border-[#2A2D30] bg-[#18191B] rounded-2xl flex flex-col gap-4 text-left">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Code size={18} className="text-[#3C6B4D]" />
            <h4 className="font-bold text-[#ECEBE9] text-sm">Automated SQL DDL Migration Script</h4>
          </div>

          <div className="flex items-center gap-2">
            <select
              value={sqlDialect}
              onChange={(e) => setSqlDialect(e.target.value as any)}
              className="bg-[#111213] border border-[#2A2D30] text-[#ECEBE9] text-xs p-2 rounded-xl cursor-pointer font-mono"
            >
              <option value="postgres">PostgreSQL</option>
              <option value="mysql">MySQL</option>
              <option value="sqlite">SQLite</option>
            </select>
            <button
              onClick={handleDownloadDiffReport}
              className="flex items-center gap-1 bg-[#111213] border border-[#2A2D30] hover:border-[#3C6B4D] text-[#ECEBE9] text-xs px-3 py-2 rounded-xl transition cursor-pointer font-semibold"
            >
              <FileText size={14} />
              Export Report
            </button>
            <button
              onClick={handleDownloadMigrationSql}
              className="flex items-center gap-1 bg-[#3C6B4D] hover:bg-[#3C6B4D]/80 text-white text-xs font-semibold px-3 py-2 rounded-xl transition cursor-pointer"
            >
              <Download size={14} />
              Export .SQL
            </button>
          </div>
        </div>

        <div className="bg-[#111213] p-4 rounded-xl border border-[#2A2D30] font-mono text-xs text-[#ECEBE9] overflow-x-auto">
          <pre>{sqlScript}</pre>
        </div>
      </div>

      {/* Local AI Data Drift Diagnostic */}
      <div className="glass-card p-6 border-[#2A2D30] bg-[#18191B] rounded-2xl flex flex-col gap-4 text-left">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2 text-[#3C6B4D]">
            <Sparkles size={18} />
            <h4 className="font-bold text-[#ECEBE9] text-sm">Local AI Data Drift & Schema Diagnostic Auditor</h4>
          </div>
          <button
            onClick={handleRunAiDataDiff}
            disabled={isAnalyzing || !selectedModel}
            className="flex items-center gap-2 bg-[#3C6B4D] hover:bg-[#3C6B4D]/80 disabled:opacity-50 text-white text-xs font-semibold px-4 py-2 rounded-xl transition cursor-pointer"
          >
            {isAnalyzing ? <RefreshCw className="animate-spin" size={14} /> : <Sparkles size={14} />}
            {isAnalyzing ? 'Analyzing Schema Drift...' : 'Run Local AI Drift Audit'}
          </button>
        </div>

        {error && <div className="p-3 bg-rose-500/10 border border-rose-500/20 rounded-xl text-rose-400 text-xs">{error}</div>}

        {aiOutput && (
          <div
            className="bg-[#111213] p-5 rounded-xl border border-[#2A2D30] text-[#ECEBE9] text-xs leading-relaxed overflow-x-auto"
            dangerouslySetInnerHTML={{ __html: parseMarkdown(aiOutput) }}
          />
        )}
      </div>
    </div>
  );
};
