import type { TemplateData } from './types';

export const PRESET_TEMPLATES: Record<string, TemplateData> = {
  employee_id: {
    id: 'preset-employee-id',
    name: 'Employee ID Card',
    width: 600,
    height: 900,
    bgImage: null, // User can set their own background
    layers: [
      {
        id: 'img-1',
        type: 'image',
        name: 'Profile Photo',
        x: 150,
        y: 100,
        width: 300,
        height: 300,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 1,
        src: null,
        placeholder: 'Profile Photo',
        variableName: '{{photo_url}}'
      },
      {
        id: 'text-1',
        type: 'text',
        name: 'Employee Name',
        x: 50,
        y: 450,
        width: 500,
        height: 50,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 2,
        text: 'John Doe',
        placeholder: '',
        variableName: '{{name}}',
        fontFamily: 'Impact',
        fontSize: 48,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textDecoration: 'none',
        fill: '#ffffff',
        backgroundColor: null,
        align: 'center',
        letterSpacing: 2,
        lineHeight: 1,
        stroke: '#000000',
        strokeWidth: 2,
        shadowColor: null,
        shadowBlur: 0,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
        textTransform: 'uppercase'
      },
      {
        id: 'text-2',
        type: 'text',
        name: 'Job Title',
        x: 50,
        y: 520,
        width: 500,
        height: 40,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 3,
        text: 'Software Engineer',
        placeholder: '',
        variableName: '{{title}}',
        fontFamily: 'Arial',
        fontSize: 24,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textDecoration: 'none',
        fill: '#cccccc',
        backgroundColor: null,
        align: 'center',
        letterSpacing: 1,
        lineHeight: 1,
        stroke: null,
        strokeWidth: 0,
        shadowColor: null,
        shadowBlur: 0,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
        textTransform: 'none'
      },
      {
        id: 'qr-1',
        type: 'qr',
        name: 'Employee QR',
        x: 225,
        y: 600,
        width: 150,
        height: 150,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 4,
        text: 'EMP-001',
        variableName: '{{employee_id}}',
        fgColor: '#000000',
        bgColor: '#ffffff'
      }
    ]
  },
  event_ticket: {
    id: 'preset-event-ticket',
    name: 'Event Ticket',
    width: 1200,
    height: 400,
    bgImage: null,
    layers: [
      {
        id: 'text-3',
        type: 'text',
        name: 'Event Title',
        x: 50,
        y: 50,
        width: 800,
        height: 80,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 1,
        text: 'ANNUAL TECH CONFERENCE 2026',
        placeholder: '',
        variableName: '{{event_name}}',
        fontFamily: 'Impact',
        fontSize: 64,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textDecoration: 'none',
        fill: '#FFD700',
        backgroundColor: null,
        align: 'left',
        letterSpacing: 4,
        lineHeight: 1,
        stroke: '#000000',
        strokeWidth: 4,
        shadowColor: null,
        shadowBlur: 0,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
        textTransform: 'uppercase'
      },
      {
        id: 'text-4',
        type: 'text',
        name: 'Attendee Name',
        x: 50,
        y: 180,
        width: 500,
        height: 50,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 2,
        text: 'Jane Smith',
        placeholder: '',
        variableName: '{{attendee_name}}',
        fontFamily: 'Georgia',
        fontSize: 36,
        fontWeight: 'normal',
        fontStyle: 'italic',
        textDecoration: 'none',
        fill: '#ffffff',
        backgroundColor: null,
        align: 'left',
        letterSpacing: 0,
        lineHeight: 1,
        stroke: null,
        strokeWidth: 0,
        shadowColor: null,
        shadowBlur: 0,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
        textTransform: 'none'
      },
      {
        id: 'barcode-1',
        type: 'barcode',
        name: 'Ticket Barcode',
        x: 900,
        y: 100,
        width: 250,
        height: 100,
        rotation: 90,
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 3,
        text: 'TKT-998877',
        variableName: '{{ticket_code}}',
        format: 'CODE128',
        lineColor: '#000000',
        bgColor: '#ffffff',
        displayValue: true
      }
    ]
  }
};
